// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: grid.sql

package griddb

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const completePeriod = `-- name: CompletePeriod :exec
UPDATE periods SET status = 'completed', ended_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) CompletePeriod(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, completePeriod, id)
	return err
}

const countTilesByStatus = `-- name: CountTilesByStatus :one
SELECT
    count(*) FILTER (WHERE status = 'drawn') AS drawn_count,
    count(*) AS total_count
FROM tiles
WHERE period_id = $1 AND phase = $2
`

type CountTilesByStatusParams struct {
	PeriodID uuid.UUID `json:"period_id"`
	Phase    int32     `json:"phase"`
}

type CountTilesByStatusRow struct {
	DrawnCount int64 `json:"drawn_count"`
	TotalCount int64 `json:"total_count"`
}

func (q *Queries) CountTilesByStatus(ctx context.Context, arg CountTilesByStatusParams) (CountTilesByStatusRow, error) {
	row := q.db.QueryRowContext(ctx, countTilesByStatus, arg.PeriodID, arg.Phase)
	var i CountTilesByStatusRow
	err := row.Scan(&i.DrawnCount, &i.TotalCount)
	return i, err
}

const createPeriod = `-- name: CreatePeriod :one
INSERT INTO periods (daily_image_id, game_type, status, phase)
VALUES ($1, $2, $3, $4)
RETURNING id, daily_image_id, game_type, status, phase, started_at, ended_at, created_at, updated_at, final_image_key, composed_at
`

type CreatePeriodParams struct {
	DailyImageID uuid.UUID `json:"daily_image_id"`
	GameType     string    `json:"game_type"`
	Status       string    `json:"status"`
	Phase        int32     `json:"phase"`
}

func (q *Queries) CreatePeriod(ctx context.Context, arg CreatePeriodParams) (Period, error) {
	row := q.db.QueryRowContext(ctx, createPeriod,
		arg.DailyImageID,
		arg.GameType,
		arg.Status,
		arg.Phase,
	)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.DailyImageID,
		&i.GameType,
		&i.Status,
		&i.Phase,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalImageKey,
		&i.ComposedAt,
	)
	return i, err
}

const createTile = `-- name: CreateTile :one
INSERT INTO tiles (period_id, phase, row_index, col_index, status)
VALUES ($1, $2, $3, $4, 'free')
RETURNING id, period_id, phase, row_index, col_index, status, created_at, updated_at
`

type CreateTileParams struct {
	PeriodID uuid.UUID `json:"period_id"`
	Phase    int32     `json:"phase"`
	RowIndex int32     `json:"row_index"`
	ColIndex int32     `json:"col_index"`
}

func (q *Queries) CreateTile(ctx context.Context, arg CreateTileParams) (Tile, error) {
	row := q.db.QueryRowContext(ctx, createTile,
		arg.PeriodID,
		arg.Phase,
		arg.RowIndex,
		arg.ColIndex,
	)
	var i Tile
	err := row.Scan(
		&i.ID,
		&i.PeriodID,
		&i.Phase,
		&i.RowIndex,
		&i.ColIndex,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePeriod = `-- name: GetActivePeriod :one
SELECT p.id, p.daily_image_id, p.game_type, p.status, p.phase,
       p.started_at, p.ended_at, p.created_at, p.updated_at,
       p.final_image_key, p.composed_at
FROM periods p
WHERE p.status = 'active'
LIMIT 1
`

func (q *Queries) GetActivePeriod(ctx context.Context) (Period, error) {
	row := q.db.QueryRowContext(ctx, getActivePeriod)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.DailyImageID,
		&i.GameType,
		&i.Status,
		&i.Phase,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalImageKey,
		&i.ComposedAt,
	)
	return i, err
}

const getGridConfig = `-- name: GetGridConfig :one
SELECT id, phase, columns, rows, created_at
FROM grid_configs
WHERE phase = $1
`

func (q *Queries) GetGridConfig(ctx context.Context, phase int32) (GridConfig, error) {
	row := q.db.QueryRowContext(ctx, getGridConfig, phase)
	var i GridConfig
	err := row.Scan(
		&i.ID,
		&i.Phase,
		&i.Columns,
		&i.Rows,
		&i.CreatedAt,
	)
	return i, err
}

const getPeriodByID = `-- name: GetPeriodByID :one
SELECT id, daily_image_id, game_type, status, phase,
       started_at, ended_at, created_at, updated_at,
       final_image_key, composed_at
FROM periods
WHERE id = $1
`

func (q *Queries) GetPeriodByID(ctx context.Context, id uuid.UUID) (Period, error) {
	row := q.db.QueryRowContext(ctx, getPeriodByID, id)
	var i Period
	err := row.Scan(
		&i.ID,
		&i.DailyImageID,
		&i.GameType,
		&i.Status,
		&i.Phase,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalImageKey,
		&i.ComposedAt,
	)
	return i, err
}

const getTilesByPeriodAndPhase = `-- name: GetTilesByPeriodAndPhase :many
SELECT t.id, t.period_id, t.phase, t.row_index, t.col_index, t.status,
       COALESCE(s.storage_key, '') AS submission_key,
       t.created_at, t.updated_at
FROM tiles t
LEFT JOIN submissions s ON s.tile_id = t.id
WHERE t.period_id = $1 AND t.phase = $2
ORDER BY t.row_index, t.col_index
`

type GetTilesByPeriodAndPhaseParams struct {
	PeriodID uuid.UUID `json:"period_id"`
	Phase    int32     `json:"phase"`
}

type GetTilesByPeriodAndPhaseRow struct {
	ID            uuid.UUID `json:"id"`
	PeriodID      uuid.UUID `json:"period_id"`
	Phase         int32     `json:"phase"`
	RowIndex      int32     `json:"row_index"`
	ColIndex      int32     `json:"col_index"`
	Status        string    `json:"status"`
	SubmissionKey string    `json:"submission_key"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) GetTilesByPeriodAndPhase(ctx context.Context, arg GetTilesByPeriodAndPhaseParams) ([]GetTilesByPeriodAndPhaseRow, error) {
	rows, err := q.db.QueryContext(ctx, getTilesByPeriodAndPhase, arg.PeriodID, arg.Phase)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTilesByPeriodAndPhaseRow
	for rows.Next() {
		var i GetTilesByPeriodAndPhaseRow
		if err := rows.Scan(
			&i.ID,
			&i.PeriodID,
			&i.Phase,
			&i.RowIndex,
			&i.ColIndex,
			&i.Status,
			&i.SubmissionKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedPeriods = `-- name: ListCompletedPeriods :many
SELECT id, daily_image_id, game_type, status, phase,
       started_at, ended_at, created_at, updated_at,
       final_image_key, composed_at
FROM periods
WHERE final_image_key IS NOT NULL
ORDER BY started_at DESC
LIMIT $1 OFFSET $2
`

type ListCompletedPeriodsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Lists periods that have a composed mosaic. Includes both completed and
// still-active periods, so today's in-progress mosaic appears in the archive.
func (q *Queries) ListCompletedPeriods(ctx context.Context, arg ListCompletedPeriodsParams) ([]Period, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedPeriods, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Period
	for rows.Next() {
		var i Period
		if err := rows.Scan(
			&i.ID,
			&i.DailyImageID,
			&i.GameType,
			&i.Status,
			&i.Phase,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinalImageKey,
			&i.ComposedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedPeriodsMissingFinalImage = `-- name: ListCompletedPeriodsMissingFinalImage :many
SELECT id, daily_image_id, game_type, status, phase,
       started_at, ended_at, created_at, updated_at,
       final_image_key, composed_at
FROM periods
WHERE status = 'completed' AND final_image_key IS NULL
ORDER BY ended_at DESC
`

func (q *Queries) ListCompletedPeriodsMissingFinalImage(ctx context.Context) ([]Period, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedPeriodsMissingFinalImage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Period
	for rows.Next() {
		var i Period
		if err := rows.Scan(
			&i.ID,
			&i.DailyImageID,
			&i.GameType,
			&i.Status,
			&i.Phase,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinalImageKey,
			&i.ComposedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMosaicsByPeriod = `-- name: ListMosaicsByPeriod :many
SELECT period_id, phase, storage_key, composed_at
FROM period_mosaics
WHERE period_id = $1
ORDER BY phase ASC
`

func (q *Queries) ListMosaicsByPeriod(ctx context.Context, periodID uuid.UUID) ([]PeriodMosaic, error) {
	rows, err := q.db.QueryContext(ctx, listMosaicsByPeriod, periodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodMosaic
	for rows.Next() {
		var i PeriodMosaic
		if err := rows.Scan(
			&i.PeriodID,
			&i.Phase,
			&i.StorageKey,
			&i.ComposedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPeriodFinalImage = `-- name: SetPeriodFinalImage :exec
UPDATE periods
SET final_image_key = $2, composed_at = now(), updated_at = now()
WHERE id = $1
`

type SetPeriodFinalImageParams struct {
	ID            uuid.UUID      `json:"id"`
	FinalImageKey sql.NullString `json:"final_image_key"`
}

func (q *Queries) SetPeriodFinalImage(ctx context.Context, arg SetPeriodFinalImageParams) error {
	_, err := q.db.ExecContext(ctx, setPeriodFinalImage, arg.ID, arg.FinalImageKey)
	return err
}

const updatePeriodPhase = `-- name: UpdatePeriodPhase :exec
UPDATE periods SET phase = $2, updated_at = now() WHERE id = $1
`

type UpdatePeriodPhaseParams struct {
	ID    uuid.UUID `json:"id"`
	Phase int32     `json:"phase"`
}

func (q *Queries) UpdatePeriodPhase(ctx context.Context, arg UpdatePeriodPhaseParams) error {
	_, err := q.db.ExecContext(ctx, updatePeriodPhase, arg.ID, arg.Phase)
	return err
}

const updateTileStatus = `-- name: UpdateTileStatus :exec
UPDATE tiles SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateTileStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTileStatus(ctx context.Context, arg UpdateTileStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTileStatus, arg.ID, arg.Status)
	return err
}

const upsertPeriodMosaic = `-- name: UpsertPeriodMosaic :exec
INSERT INTO period_mosaics (period_id, phase, storage_key)
VALUES ($1, $2, $3)
ON CONFLICT (period_id, phase) DO UPDATE
SET storage_key = EXCLUDED.storage_key,
    composed_at = now()
`

type UpsertPeriodMosaicParams struct {
	PeriodID   uuid.UUID `json:"period_id"`
	Phase      int32     `json:"phase"`
	StorageKey string    `json:"storage_key"`
}

func (q *Queries) UpsertPeriodMosaic(ctx context.Context, arg UpsertPeriodMosaicParams) error {
	_, err := q.db.ExecContext(ctx, upsertPeriodMosaic, arg.PeriodID, arg.Phase, arg.StorageKey)
	return err
}
