// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedback.sql

package feedbackdb

import (
	"context"
)

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedback (message, contact)
VALUES ($1, $2)
RETURNING id, message, contact, created_at
`

type CreateFeedbackParams struct {
	Message string `json:"message"`
	Contact string `json:"contact"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRowContext(ctx, createFeedback, arg.Message, arg.Contact)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.Contact,
		&i.CreatedAt,
	)
	return i, err
}

const listFeedback = `-- name: ListFeedback :many
SELECT id, message, contact, created_at
FROM feedback
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListFeedbackParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFeedback(ctx context.Context, arg ListFeedbackParams) ([]Feedback, error) {
	rows, err := q.db.QueryContext(ctx, listFeedback, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feedback
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.Contact,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
