// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package feedbackdb

import (
	"context"
)

type Querier interface {
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error)
	ListFeedback(ctx context.Context, arg ListFeedbackParams) ([]Feedback, error)
}

var _ Querier = (*Queries)(nil)
