// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: claims.sql

package claimdb

import (
	"context"

	"github.com/google/uuid"
)

const getActiveClaimBySessionAndTile = `-- name: GetActiveClaimBySessionAndTile :one
SELECT id, tile_id, nickname, session_id, claimed_at, expires_at, released_at, created_at
FROM claims
WHERE tile_id = $1 AND session_id = $2 AND released_at IS NULL
`

type GetActiveClaimBySessionAndTileParams struct {
	TileID    uuid.UUID `json:"tile_id"`
	SessionID string    `json:"session_id"`
}

func (q *Queries) GetActiveClaimBySessionAndTile(ctx context.Context, arg GetActiveClaimBySessionAndTileParams) (Claim, error) {
	row := q.db.QueryRowContext(ctx, getActiveClaimBySessionAndTile, arg.TileID, arg.SessionID)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.TileID,
		&i.Nickname,
		&i.SessionID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getClaimByTileID = `-- name: GetClaimByTileID :one
SELECT id, tile_id, nickname, session_id, claimed_at, expires_at, released_at, created_at
FROM claims
WHERE tile_id = $1 AND released_at IS NULL
`

func (q *Queries) GetClaimByTileID(ctx context.Context, tileID uuid.UUID) (Claim, error) {
	row := q.db.QueryRowContext(ctx, getClaimByTileID, tileID)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.TileID,
		&i.Nickname,
		&i.SessionID,
		&i.ClaimedAt,
		&i.ExpiresAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}
