// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package claimdb

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Claim struct {
	ID              uuid.UUID    `json:"id"`
	TileID          uuid.UUID    `json:"tile_id"`
	Nickname        string       `json:"nickname"`
	SessionID       string       `json:"session_id"`
	ClaimedAt       time.Time    `json:"claimed_at"`
	ExpiresAt       time.Time    `json:"expires_at"`
	ReleasedAt      sql.NullTime `json:"released_at"`
	CreatedAt       time.Time    `json:"created_at"`
	LastHeartbeatAt time.Time    `json:"last_heartbeat_at"`
}

type DailyImage struct {
	ID         uuid.UUID `json:"id"`
	Date       time.Time `json:"date"`
	StorageKey string    `json:"storage_key"`
	Width      int32     `json:"width"`
	Height     int32     `json:"height"`
	IsActive   bool      `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type DailyImageSchedule struct {
	Date       time.Time `json:"date"`
	StorageKey string    `json:"storage_key"`
	Width      int32     `json:"width"`
	Height     int32     `json:"height"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type DailyPromptSchedule struct {
	Date      time.Time `json:"date"`
	Prompt    string    `json:"prompt"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Feedback struct {
	ID        uuid.UUID `json:"id"`
	Message   string    `json:"message"`
	Contact   string    `json:"contact"`
	CreatedAt time.Time `json:"created_at"`
}

type GridConfig struct {
	ID        uuid.UUID `json:"id"`
	Phase     int32     `json:"phase"`
	Columns   int32     `json:"columns"`
	Rows      int32     `json:"rows"`
	CreatedAt time.Time `json:"created_at"`
}

type Period struct {
	ID            uuid.UUID      `json:"id"`
	DailyImageID  uuid.NullUUID  `json:"daily_image_id"`
	GameType      string         `json:"game_type"`
	Status        string         `json:"status"`
	Phase         int32          `json:"phase"`
	StartedAt     time.Time      `json:"started_at"`
	EndedAt       sql.NullTime   `json:"ended_at"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	FinalImageKey sql.NullString `json:"final_image_key"`
	ComposedAt    sql.NullTime   `json:"composed_at"`
	Prompt        sql.NullString `json:"prompt"`
}

type PeriodMosaic struct {
	PeriodID   uuid.UUID `json:"period_id"`
	Phase      int32     `json:"phase"`
	StorageKey string    `json:"storage_key"`
	ComposedAt time.Time `json:"composed_at"`
}

type SchemaInfo struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Submission struct {
	ID               uuid.UUID    `json:"id"`
	TileID           uuid.UUID    `json:"tile_id"`
	ClaimID          uuid.UUID    `json:"claim_id"`
	StorageKey       string       `json:"storage_key"`
	CropX            float64      `json:"crop_x"`
	CropY            float64      `json:"crop_y"`
	CropWidth        float64      `json:"crop_width"`
	CropHeight       float64      `json:"crop_height"`
	CreatedAt        time.Time    `json:"created_at"`
	StorageCleanedAt sql.NullTime `json:"storage_cleaned_at"`
}

type Tile struct {
	ID        uuid.UUID `json:"id"`
	PeriodID  uuid.UUID `json:"period_id"`
	Phase     int32     `json:"phase"`
	RowIndex  int32     `json:"row_index"`
	ColIndex  int32     `json:"col_index"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
