// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package claimdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetActiveClaimBySessionAndTile(ctx context.Context, arg GetActiveClaimBySessionAndTileParams) (Claim, error)
	GetClaimByTileID(ctx context.Context, tileID uuid.UUID) (Claim, error)
}

var _ Querier = (*Queries)(nil)
