// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package submissiondb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetSubmissionByTileID(ctx context.Context, tileID uuid.UUID) (Submission, error)
	ListSubmissionsByPeriodAndPhase(ctx context.Context, arg ListSubmissionsByPeriodAndPhaseParams) ([]Submission, error)
}

var _ Querier = (*Queries)(nil)
