// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package submissiondb

import (
	"context"

	"github.com/google/uuid"
)

const getSubmissionByTileID = `-- name: GetSubmissionByTileID :one
SELECT id, tile_id, claim_id, storage_key, crop_x, crop_y, crop_width, crop_height, created_at
FROM submissions
WHERE tile_id = $1
`

func (q *Queries) GetSubmissionByTileID(ctx context.Context, tileID uuid.UUID) (Submission, error) {
	row := q.db.QueryRowContext(ctx, getSubmissionByTileID, tileID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TileID,
		&i.ClaimID,
		&i.StorageKey,
		&i.CropX,
		&i.CropY,
		&i.CropWidth,
		&i.CropHeight,
		&i.CreatedAt,
	)
	return i, err
}

const listSubmissionsByPeriodAndPhase = `-- name: ListSubmissionsByPeriodAndPhase :many
SELECT s.id, s.tile_id, s.claim_id, s.storage_key,
       s.crop_x, s.crop_y, s.crop_width, s.crop_height, s.created_at
FROM submissions s
JOIN tiles t ON t.id = s.tile_id
WHERE t.period_id = $1 AND t.phase = $2
`

type ListSubmissionsByPeriodAndPhaseParams struct {
	PeriodID uuid.UUID `json:"period_id"`
	Phase    int32     `json:"phase"`
}

func (q *Queries) ListSubmissionsByPeriodAndPhase(ctx context.Context, arg ListSubmissionsByPeriodAndPhaseParams) ([]Submission, error) {
	rows, err := q.db.QueryContext(ctx, listSubmissionsByPeriodAndPhase, arg.PeriodID, arg.Phase)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.TileID,
			&i.ClaimID,
			&i.StorageKey,
			&i.CropX,
			&i.CropY,
			&i.CropWidth,
			&i.CropHeight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
