// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_images.sql

package dailyimagedb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deactivateAllDailyImages = `-- name: DeactivateAllDailyImages :exec
UPDATE daily_images SET is_active = false, updated_at = now()
WHERE is_active = true
`

func (q *Queries) DeactivateAllDailyImages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deactivateAllDailyImages)
	return err
}

const getActiveDailyImage = `-- name: GetActiveDailyImage :one
SELECT id, date, storage_key, width, height, is_active, created_at, updated_at
FROM daily_images
WHERE is_active = true
LIMIT 1
`

func (q *Queries) GetActiveDailyImage(ctx context.Context) (DailyImage, error) {
	row := q.db.QueryRowContext(ctx, getActiveDailyImage)
	var i DailyImage
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyImageByDate = `-- name: GetDailyImageByDate :one
SELECT id, date, storage_key, width, height, is_active, created_at, updated_at
FROM daily_images
WHERE date = $1
`

func (q *Queries) GetDailyImageByDate(ctx context.Context, date time.Time) (DailyImage, error) {
	row := q.db.QueryRowContext(ctx, getDailyImageByDate, date)
	var i DailyImage
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyImageByID = `-- name: GetDailyImageByID :one
SELECT id, date, storage_key, width, height, is_active, created_at, updated_at
FROM daily_images
WHERE id = $1
`

func (q *Queries) GetDailyImageByID(ctx context.Context, id uuid.UUID) (DailyImage, error) {
	row := q.db.QueryRowContext(ctx, getDailyImageByID, id)
	var i DailyImage
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDailyImage = `-- name: UpsertDailyImage :one
INSERT INTO daily_images (date, storage_key, width, height, is_active)
VALUES ($1, $2, $3, $4, true)
ON CONFLICT (date) DO UPDATE
    SET storage_key = EXCLUDED.storage_key,
        width       = EXCLUDED.width,
        height      = EXCLUDED.height,
        is_active   = true,
        updated_at  = now()
RETURNING id, date, storage_key, width, height, is_active, created_at, updated_at
`

type UpsertDailyImageParams struct {
	Date       time.Time `json:"date"`
	StorageKey string    `json:"storage_key"`
	Width      int32     `json:"width"`
	Height     int32     `json:"height"`
}

func (q *Queries) UpsertDailyImage(ctx context.Context, arg UpsertDailyImageParams) (DailyImage, error) {
	row := q.db.QueryRowContext(ctx, upsertDailyImage,
		arg.Date,
		arg.StorageKey,
		arg.Width,
		arg.Height,
	)
	var i DailyImage
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
